### ISSUE TITLE
sftp上传文件报错 另外希望支持拖到上传

### ISSUE THREAD

**Issue by qian9008** [1Remote/1Remote#393]
<details>

## Environment

|     Component   |                       Version                      |
|:------------------|:--------------------------------------|
|PRemoteM | `0.7.2.8`(EXE Release)|
|.NET Framework | ``    |
|CLR            | `6.0.16`       |
|OS             | `Windows 10 Enterprise 64-bits 10.0.20348.0 (2009)`                  |

## Error Info

Value cannot be null. (Parameter 'fileName')

## Stack Trace

```
   at Renci.SshNet.PrivateKeyFile..ctor(String fileName, String passPhrase)
   at Renci.SshNet.PrivateKeyFile..ctor(String fileName)
   at PRM.Model.Protocol.FileTransmit.Transmitters.TransmitterSFtp.InitClient() in D:\a\1Remote\1Remote\Ui\Model\Protocol\FileTransmit\Transmitters\TransmitterSFtp.cs:line 305
   at PRM.Model.Protocol.FileTransmit.Transmitters.TransmitterSFtp..ctor(String host, Int32 port, String username, String key, Boolean keyIsPassword) in D:\a\1Remote\1Remote\Ui\Model\Protocol\FileTransmit\Transmitters\TransmitterSFtp.cs:line 39
   at PRM.Model.Protocol.FileTransmit.Transmitters.TransmitterSFtp.Clone() in D:\a\1Remote\1Remote\Ui\Model\Protocol\FileTransmit\Transmitters\TransmitterSFtp.cs:line 71
   at PRM.Model.Protocol.FileTransmit.Transmitters.TransmissionController.TransmitTask.StartTransmitAsync(IEnumerable`1 remoteItems) in D:\a\1Remote\1Remote\Ui\Model\Protocol\FileTransmit\Transmitters\TransmissionController\TransmitTask.cs:line 378
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

## Recent Log 

```
[T:012][08:37:55.104]	`Warning`		[SessionControlService.cs(<CloseProtocolHostAsync>b__0:698)]	CloseEmptyWindows: 1 Empty Host closed
[T:007][20:32:21.384]	`Warning`		[SessionControlService.cs(<CloseProtocolHostAsync>b__0:698)]	CloseEmptyWindows: 1 Empty Host closed
[T:001][20:35:55.436]	`Fatal`		[Bootstrapper.cs(OnUnhandledException:164)]	
> System.ArgumentNullException: Value cannot be null. (Parameter 'fileName')
   at Renci.SshNet.PrivateKeyFile..ctor(String fileName, String passPhrase)
   at Renci.SshNet.PrivateKeyFile..ctor(String fileName)
   at PRM.Model.Protocol.FileTransmit.Transmitters.TransmitterSFtp.InitClient() in D:\a\1Remote\1Remote\Ui\Model\Protocol\FileTransmit\Transmitters\TransmitterSFtp.cs:line 305
   at PRM.Model.Protocol.FileTransmit.Transmitters.TransmitterSFtp..ctor(String host, Int32 port, String username, String key, Boolean keyIsPassword) in D:\a\1Remote\1Remote\Ui\Model\Protocol\FileTransmit\Transmitters\TransmitterSFtp.cs:line 39
   at PRM.Model.Protocol.FileTransmit.Transmitters.TransmitterSFtp.Clone() in D:\a\1Remote\1Remote\Ui\Model\Protocol\FileTransmit\Transmitters\TransmitterSFtp.cs:line 71
   at PRM.Model.Protocol.FileTransmit.Transmitters.TransmissionController.TransmitTask.StartTransmitAsync(IEnumerable`1 remoteItems) in D:\a\1Remote\1Remote\Ui\Model\Protocol\FileTransmit\Transmitters\TransmissionController\TransmitTask.cs:line 378
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
> StackTrace:    at Renci.SshNet.PrivateKeyFile..ctor(String fileName, String passPhrase)
   at Renci.SshNet.PrivateKeyFile..ctor(String fileName)
   at PRM.Model.Protocol.FileTransmit.Transmitters.TransmitterSFtp.InitClient() in D:\a\1Remote\1Remote\Ui\Model\Protocol\FileTransmit\Transmitters\TransmitterSFtp.cs:line 305
   at PRM.Model.Protocol.FileTransmit.Transmitters.TransmitterSFtp..ctor(String host, Int32 port, String username, String key, Boolean keyIsPassword) in D:\a\1Remote\1Remote\Ui\Model\Protocol\FileTransmit\Transmitters\TransmitterSFtp.cs:line 39
   at PRM.Model.Protocol.FileTransmit.Transmitters.TransmitterSFtp.Clone() in D:\a\1Remote\1Remote\Ui\Model\Protocol\FileTransmit\Transmitters\TransmitterSFtp.cs:line 71
   at PRM.Model.Protocol.FileTransmit.Transmitters.TransmissionController.TransmitTask.StartTransmitAsync(IEnumerable`1 remoteItems) in D:\a\1Remote\1Remote\Ui\Model\Protocol\FileTransmit\Transmitters\TransmissionController\TransmitTask.cs:line 378
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
[T:001][20:36:43.081]	`Fatal`		[Bootstrapper.cs(OnUnhandledException:164)]	
> System.ArgumentNullException: Value cannot be null. (Parameter 'fileName')
   at Renci.SshNet.PrivateKeyFile..ctor(String fileName, String passPhrase)
   at Renci.SshNet.PrivateKeyFile..ctor(String fileName)
   at PRM.Model.Protocol.FileTransmit.Transmitters.TransmitterSFtp.InitClient() in D:\a\1Remote\1Remote\Ui\Model\Protocol\FileTransmit\Transmitters\TransmitterSFtp.cs:line 305
   at PRM.Model.Protocol.FileTransmit.Transmitters.TransmitterSFtp..ctor(String host, Int32 port, String username, String key, Boolean keyIsPassword) in D:\a\1Remote\1Remote\Ui\Model\Protocol\FileTransmit\Transmitters\TransmitterSFtp.cs:line 39
   at PRM.Model.Protocol.FileTransmit.Transmitters.TransmitterSFtp.Clone() in D:\a\1Remote\1Remote\Ui\Model\Protocol\FileTransmit\Transmitters\TransmitterSFtp.cs:line 71
   at PRM.Model.Protocol.FileTransmit.Transmitters.TransmissionController.TransmitTask.StartTransmitAsync(IEnumerable`1 remoteItems) in D:\a\1Remote\1Remote\Ui\Model\Protocol\FileTransmit\Transmitters\TransmissionController\TransmitTask.cs:line 378
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
> StackTrace:    at Renci.SshNet.PrivateKeyFile..ctor(String fileName, String passPhrase)
   at Renci.SshNet.PrivateKeyFile..ctor(String fileName)
   at PRM.Model.Protocol.FileTransmit.Transmitters.TransmitterSFtp.InitClient() in D:\a\1Remote\1Remote\Ui\Model\Protocol\FileTransmit\Transmitters\TransmitterSFtp.cs:line 305
   at PRM.Model.Protocol.FileTransmit.Transmitters.TransmitterSFtp..ctor(String host, Int32 port, String username, String key, Boolean keyIsPassword) in D:\a\1Remote\1Remote\Ui\Model\Protocol\FileTransmit\Transmitters\TransmitterSFtp.cs:line 39
   at PRM.Model.Protocol.FileTransmit.Transmitters.TransmitterSFtp.Clone() in D:\a\1Remote\1Remote\Ui\Model\Protocol\FileTransmit\Transmitters\TransmitterSFtp.cs:line 71
   at PRM.Model.Protocol.FileTransmit.Transmitters.TransmissionController.TransmitTask.StartTransmitAsync(IEnumerable`1 remoteItems) in D:\a\1Remote\1Remote\Ui\Model\Protocol\FileTransmit\Transmitters\TransmissionController\TransmitTask.cs:line 378
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

```

</details>

**Comment by VShawn** [comment]
thx for reporting, it has been fixed and drag upload is supported now on our pre publish
