### ISSUE TITLE
Crash when connecting

### ISSUE THREAD

**Issue by majkinetor** [1Remote/1Remote#397]
Trying to connect to a server I connect all the time, it shows a popup that credentials are required and then crashes consistently.

I noticed that remote computer (with Windows 10) is on login screen and that when I physically login, I can connect to it without a crash.

<details><summary>details</summary> 

Log shows only this message: `[T:014][23:21:20.367]	`Info`		Auto switching address.`

Event viewer shows those 2 errors:

```xml
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
    <System>
        <Provider Name=".NET Runtime" />
        <EventID Qualifiers="0">1026</EventID>
        <Version>0</Version>
        <Level>2</Level>
        <Task>0</Task>
        <Opcode>0</Opcode>
        <Keywords>0x80000000000000</Keywords>
        <TimeCreated SystemTime="2023-05-05T21:21:26.2629601Z" />
        <EventRecordID>11578</EventRecordID>
        <Correlation />
        <Execution ProcessID="4792" ThreadID="0" />
        <Channel>Application</Channel>
        <Computer>mm-omen-w11.nil.rs</Computer>
        <Security />
    </System>
    <EventData>
        <Data>Application: 1Remote.exe CoreCLR Version: 6.0.1623.17311 .NET Version: 6.0.16
            Description: The process was terminated due to an unhandled exception.
            Exception Info: System.Runtime.InteropServices.SEHException (0x80004005): External
            component has thrown an exception.
            at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
            at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
            at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame) at
            System.Windows.Threading.Dispatcher.Run()
            at System.Windows.Application.RunDispatcher(Object ignore) at
            System.Windows.Application.RunInternal(Window window)
            at System.Windows.Application.Run() at _1RM.App.Main()
        </Data>
    </EventData>
</Event>

```

```xml
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
    <System>
        <Provider Name="Application Error" Guid="{a0e9b465-b939-57d7-b27d-95d8e925ff57}" />
        <EventID>1000</EventID>
        <Version>0</Version>
        <Level>2</Level>
        <Task>100</Task>
        <Opcode>0</Opcode>
        <Keywords>0x8000000000000000</Keywords>
        <TimeCreated SystemTime="2023-05-05T21:21:26.6340057Z" />
        <EventRecordID>11579</EventRecordID>
        <Correlation />
        <Execution ProcessID="21592" ThreadID="16996" />
        <Channel>Application</Channel>
        <Computer>mm-omen-w11.nil.rs</Computer>
        <Security UserID="S-1-5-21-2618873275-1807755624-3557091709-1004" />
    </System>
    <EventData>
        <Data Name="AppName">1Remote.exe</Data>
        <Data Name="AppVersion">1.0.0.0</Data>
        <Data Name="AppTimeStamp">63ed8286</Data>
        <Data Name="ModuleName">KERNELBASE.dll</Data>
        <Data Name="ModuleVersion">10.0.22621.1555</Data>
        <Data Name="ModuleTimeStamp">235a45d0</Data>
        <Data Name="ExceptionCode">c06d007f</Data>
        <Data Name="FaultingOffset">000000000008fdec</Data>
        <Data Name="ProcessId">0x12b8</Data>
        <Data Name="ProcessCreationTime">0x1d97f9787ed729e</Data>
        <Data Name="AppPath">C:\tools\1Remote\1Remote.exe</Data>
        <Data Name="ModulePath">C:\Windows\System32\KERNELBASE.dll</Data>
        <Data Name="IntegratorReportId">5979d4ad-99d2-4ef6-9445-9d314c386a4d</Data>
        <Data Name="PackageFullName" />
        <Data Name="PackageRelativeAppId" />
    </EventData>
</Event>
```
</details>

**Desktop (please complete the following information):**
 - OS: Windows 11
 - 1RemoteM Version: 1.0.0.beta3

**Comment by VShawn** [comment]
close the inactive ticket feel free to reopen it.
