### ISSUE TITLE
Problem with applications configured in RemoteApp

### ISSUE THREAD

**Issue by Lnunovero92** [1Remote/1Remote#435]
Hello dear friends
I would like to report a problem I am experiencing with the latest released Betas versions of 1Remote.
Currently I have applications configured with RemoteApp which stopped working from one day to another. At the moment when I double click on them and/or connect they simply do nothing, nor is the attempt to open a window displayed.

Interestingly when I delete my AppData hosted profile from the application and reconfigure it is when it works again.

I can't add an error image as there is no failure window that I can display.

I appreciate your support and collaboration to identify what may be going on, if you require any additional information or additional help from me please let me know.

 - OS: Win11 - 22H2
 - 1RemoteM Version: 1Remote-1.0.0.0-beta.04-net6-x64-nightly-20230606

**Comment by Lnunovero92** [comment]
Añado el log encontrado en la ruta de AppData\Roaming\1Remote\Logs del día de hoy al intentar acceder al RemoteApp:

`[T:001][13:50:16.083]	`Info`		Main window resize to: w = 800, h = 530

[T:012][13:50:22.338]	`Info`		Auto switching address.

[T:011][13:50:36.875]	`Info`		Auto switching address.

[T:001][13:50:47.363]	`Error`		[AxMsRdpClient09Host.xaml.cs(<SetRdpResolution>b__0:822)]	
> System.Runtime.InteropServices.COMException (0x8000FFFF): Error catastrófico (0x8000FFFF (E_UNEXPECTED))
   at MSTSCLib.IMsRdpClient9.UpdateSessionDisplaySettings(UInt32 ulDesktopWidth, UInt32 ulDesktopHeight, UInt32 ulPhysicalWidth, UInt32 ulPhysicalHeight, UInt32 ulOrientation, UInt32 ulDesktopScaleFactor, UInt32 ulDeviceScaleFactor)
   at AxMSTSCLib.AxMsRdpClient9NotSafeForScripting.UpdateSessionDisplaySettings(UInt32 ulDesktopWidth, UInt32 ulDesktopHeight, UInt32 ulPhysicalWidth, UInt32 ulPhysicalHeight, UInt32 ulOrientation, UInt32 ulDesktopScaleFactor, UInt32 ulDeviceScaleFactor)
   at _1RM.View.Host.ProtocolHosts.AxMsRdpClient09Host.<>c__DisplayClass51_0.<SetRdpResolution>b__0() in D:\a\1Remote\1Remote\Ui\View\Host\ProtocolHosts\AxMsRdpClient09Host.xaml.cs:line 822

> StackTrace:    at MSTSCLib.IMsRdpClient9.UpdateSessionDisplaySettings(UInt32 ulDesktopWidth, UInt32 ulDesktopHeight, UInt32 ulPhysicalWidth, UInt32 ulPhysicalHeight, UInt32 ulOrientation, UInt32 ulDesktopScaleFactor, UInt32 ulDeviceScaleFactor)
   at AxMSTSCLib.AxMsRdpClient9NotSafeForScripting.UpdateSessionDisplaySettings(UInt32 ulDesktopWidth, UInt32 ulDesktopHeight, UInt32 ulPhysicalWidth, UInt32 ulPhysicalHeight, UInt32 ulOrientation, UInt32 ulDesktopScaleFactor, UInt32 ulDeviceScaleFactor)
   at _1RM.View.Host.ProtocolHosts.AxMsRdpClient09Host.<>c__DisplayClass51_0.<SetRdpResolution>b__0() in D:\a\1Remote\1Remote\Ui\View\Host\ProtocolHosts\AxMsRdpClient09Host.xaml.cs:line 822


[T:012][13:50:47.382]	`Info`		Auto switching address.

[T:012][13:51:17.274]	`Info`		Auto switching address.

[T:022][13:51:58.194]	`Info`		Auto switching address.

[T:007][13:52:13.289]	`Info`		Auto switching address.

[T:026][13:53:15.885]	`Info`		Auto switching address.

[T:029][13:53:30.330]	`Info`		Auto switching address.

[T:019][14:13:31.999]	`Info`		Auto switching address.

[T:033][14:21:45.956]	`Info`		Auto switching address.

[T:010][14:21:46.739]	`Info`		Auto switching address.

[T:027][14:21:47.400]	`Info`		Auto switching address.

[T:037][14:21:48.061]	`Info`		Auto switching address.

[T:037][14:21:48.695]	`Info`		Auto switching address.

[T:010][14:21:49.376]	`Info`		Auto switching address.

[T:010][14:21:50.080]	`Info`		Auto switching address.

[T:017][14:21:50.725]	`Info`		Auto switching address.

[T:027][14:21:51.434]	`Info`		Auto switching address.

[T:030][14:21:52.128]	`Info`		Auto switching address.

[T:038][14:21:53.428]	`Info`		Auto switching address.

[T:041][14:21:54.194]	`Info`		Auto switching address.

[T:037][14:21:54.988]	`Info`		Auto switching address.

[T:037][14:21:55.695]	`Info`		Auto switching address.

[T:034][14:21:56.425]	`Info`		Auto switching address.

[T:034][14:21:57.198]	`Info`		Auto switching address.

[T:009][14:21:57.973]	`Info`		Auto switching address.

[T:033][14:21:58.688]	`Info`		Auto switching address.

[T:010][14:21:59.482]	`Info`		Auto switching address.

[T:010][14:22:00.157]	`Info`		Auto switching address.

[T:040][14:22:00.951]	`Info`		Auto switching address.

[T:027][14:22:01.749]	`Info`		Auto switching address.

[T:016][14:22:02.593]	`Info`		Auto switching address.

[T:013][14:22:03.516]	`Info`		Auto switching address.

[T:033][14:22:04.280]	`Info`		Auto switching address.

[T:045][14:23:59.702]	`Warning`		[SessionControlService.cs(<CloseProtocolHostAsync>b__0:179)]	CloseEmptyWindows: 1 Empty Host closed

[T:045][14:24:00.300]	`Error`		[SessionControlService.cs(CloseMarkedProtocolHost:291)]	
> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Windows.Threading.DispatcherOperation.Wait(TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.InvokeImpl(DispatcherOperation operation, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback)
   at Stylet.Execute.OnUIThreadSync(Action action)
   at _1RM.View.Host.ProtocolHosts.AxMsRdpClient09Host.RdpClientDispose() in D:\a\1Remote\1Remote\Ui\View\Host\ProtocolHosts\AxMsRdpClient09Host.xaml.cs:line 772
   at _1RM.View.Host.ProtocolHosts.AxMsRdpClient09Host.Dispose() in D:\a\1Remote\1Remote\Ui\View\Host\ProtocolHosts\AxMsRdpClient09Host.xaml.cs:line 102
   at _1RM.Service.SessionControlService.CloseMarkedProtocolHost() in D:\a\1Remote\1Remote\Ui\Service\SessionControlService.cs:line 291

> StackTrace:    at System.Windows.Threading.DispatcherOperation.Wait(TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.InvokeImpl(DispatcherOperation operation, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback)
   at Stylet.Execute.OnUIThreadSync(Action action)
   at _1RM.View.Host.ProtocolHosts.AxMsRdpClient09Host.RdpClientDispose() in D:\a\1Remote\1Remote\Ui\View\Host\ProtocolHosts\AxMsRdpClient09Host.xaml.cs:line 772
   at _1RM.View.Host.ProtocolHosts.AxMsRdpClient09Host.Dispose() in D:\a\1Remote\1Remote\Ui\View\Host\ProtocolHosts\AxMsRdpClient09Host.xaml.cs:line 102
   at _1RM.Service.SessionControlService.CloseMarkedProtocolHost() in D:\a\1Remote\1Remote\Ui\Service\SessionControlService.cs:line 291`

**Comment by Lnunovero92** [comment]
I just noticed that Beta 4 unlike Beta 3 creates .rdp files in the \AppData\Local\Temp path which get stuck running through the remote access process.

I have reverted to version 3 and after testing I see that it does not create the temporary .rdp files.

**Comment by VShawn** [comment]
hi @Lnunovero92 

The startup process of the RDP app is:

1. Create a temporary rdp file in the TMP folder.
2. Use the system built-in MSTSC.exe to run this rdp file.
3. try to delete the rdp file in the TMP folder after 10 seconds.

This process has not been modified since the initial version to the current version.

Therefore, the error in your log is actually in step 3, where the file couldn't be deleted because it was being used (since the Rdp app does not display any windows, the rdp file is likely being used by mstsc.exe). So it will not effect to the problem `simply do nothing, nor is the attempt to open a window displayed`

I will test the RDP app on the latest beta version later, and you can also try using mstsc.exe to directly start the rdp file left in the TMP folder.

**Comment by VShawn** [comment]
![image](https://github.com/1Remote/1Remote/assets/10143738/4ae3ea11-bd1f-4b15-b128-63b10358d04a)

it works as expect on my PC, my OS is Win11, so it's possible that my test results may not prove anything.

**Comment by Lnunovero92** [comment]
Hello
Sorry, I was so excited to use the tool without problems that I didn't get to confirm that with the latest release I no longer perceive the reported drawback.

Thank you for your support.
