### ISSUE TITLE
1Remote log:  unexpected error occurred

### ISSUE THREAD

**Issue by aleck31** [1Remote/1Remote#441]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - |OS             | `Windows 10 Pro 64-bits 10.0.22621.0 (2009)`                  |
 - |1Remote | `1.0.0-beta.05`(EXE Release)|

**Additional context**

<details>

## Environment

|     Component   |                       Version                      |
|:------------------|:--------------------------------------|

|.NET Framework | ``    |
|CLR            | `6.0.18`       |

## Error Info

Value cannot be null. (Parameter 'path1')

## Stack Trace

```
   at System.IO.Path.Combine(String path1, String path2)
   at System.Data.SQLite.SQLiteConnection..ctor(String connectionString, Boolean parseViaFramework)
   at System.Data.SQLite.SQLiteConnection..ctor(String connectionString)
   at _1RM.Service.DataSource.DAO.Dapper.DapperDatabase.OpenConnection(String actionInfo) in D:\a\1Remote\1Remote\Ui\Service\DataSource\DAO\Dapper\DapperDataBase.cs:line 85
   at _1RM.Service.DataSource.DAO.Dapper.DapperDatabase.OpenNewConnection(String newConnectionString) in D:\a\1Remote\1Remote\Ui\Service\DataSource\DAO\Dapper\DapperDataBase.cs:line 55
   at _1RM.Service.DataSource.Model.DataSourceBase.Database_OpenConnection(Int32 connectTimeOutSeconds) in D:\a\1Remote\1Remote\Ui\Service\DataSource\Model\DataSourceBase.Source.cs:line 166
   at _1RM.Service.DataSource.Model.DataSourceBase.Database_SelfCheck(Int32 connectTimeOutSeconds) in D:\a\1Remote\1Remote\Ui\Service\DataSource\Model\DataSourceBase.Source.cs:line 186
   at _1RM.Service.DataSource.DataSourceService.InitLocalDataSource(SqliteSource sqliteConfig) in D:\a\1Remote\1Remote\Ui\Service\DataSource\DataSourceService.cs:line 83
   at _1RM.AppInitHelper.InitOnConfigure() in D:\a\1Remote\1Remote\Ui\AppInit.cs:line 275
   at _1RM.Bootstrapper.Configure() in D:\a\1Remote\1Remote\Ui\Bootstrapper.cs:line 89
   at Stylet.BootstrapperBase.Start(String[] args)
   at Stylet.BootstrapperBase.<Setup>b__9_0(Object o, StartupEventArgs e)
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at _1RM.App.OnStartup(StartupEventArgs e) in D:\a\1Remote\1Remote\Ui\App.xaml.cs:line 58
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

## Recent Log 

```
[T:001][21:49:52.767]	`Fatal`		[Bootstrapper.cs(OnUnhandledException:139)]	
> System.ArgumentNullException: Value cannot be null. (Parameter 'path1')
   at System.IO.Path.Combine(String path1, String path2)
   at System.Data.SQLite.SQLiteConnection..ctor(String connectionString, Boolean parseViaFramework)
   at System.Data.SQLite.SQLiteConnection..ctor(String connectionString)
   at _1RM.Service.DataSource.DAO.Dapper.DapperDatabase.OpenConnection(String actionInfo) in D:\a\1Remote\1Remote\Ui\Service\DataSource\DAO\Dapper\DapperDataBase.cs:line 85
   at _1RM.Service.DataSource.DAO.Dapper.DapperDatabase.OpenNewConnection(String newConnectionString) in D:\a\1Remote\1Remote\Ui\Service\DataSource\DAO\Dapper\DapperDataBase.cs:line 55
   at _1RM.Service.DataSource.Model.DataSourceBase.Database_OpenConnection(Int32 connectTimeOutSeconds) in D:\a\1Remote\1Remote\Ui\Service\DataSource\Model\DataSourceBase.Source.cs:line 166
   at _1RM.Service.DataSource.Model.DataSourceBase.Database_SelfCheck(Int32 connectTimeOutSeconds) in D:\a\1Remote\1Remote\Ui\Service\DataSource\Model\DataSourceBase.Source.cs:line 186
   at _1RM.Service.DataSource.DataSourceService.InitLocalDataSource(SqliteSource sqliteConfig) in D:\a\1Remote\1Remote\Ui\Service\DataSource\DataSourceService.cs:line 83
   at _1RM.AppInitHelper.InitOnConfigure() in D:\a\1Remote\1Remote\Ui\AppInit.cs:line 275
   at _1RM.Bootstrapper.Configure() in D:\a\1Remote\1Remote\Ui\Bootstrapper.cs:line 89
   at Stylet.BootstrapperBase.Start(String[] args)
   at Stylet.BootstrapperBase.<Setup>b__9_0(Object o, StartupEventArgs e)
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at _1RM.App.OnStartup(StartupEventArgs e) in D:\a\1Remote\1Remote\Ui\App.xaml.cs:line 58
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
> StackTrace:    at System.IO.Path.Combine(String path1, String path2)
   at System.Data.SQLite.SQLiteConnection..ctor(String connectionString, Boolean parseViaFramework)
   at System.Data.SQLite.SQLiteConnection..ctor(String connectionString)
   at _1RM.Service.DataSource.DAO.Dapper.DapperDatabase.OpenConnection(String actionInfo) in D:\a\1Remote\1Remote\Ui\Service\DataSource\DAO\Dapper\DapperDataBase.cs:line 85
   at _1RM.Service.DataSource.DAO.Dapper.DapperDatabase.OpenNewConnection(String newConnectionString) in D:\a\1Remote\1Remote\Ui\Service\DataSource\DAO\Dapper\DapperDataBase.cs:line 55
   at _1RM.Service.DataSource.Model.DataSourceBase.Database_OpenConnection(Int32 connectTimeOutSeconds) in D:\a\1Remote\1Remote\Ui\Service\DataSource\Model\DataSourceBase.Source.cs:line 166
   at _1RM.Service.DataSource.Model.DataSourceBase.Database_SelfCheck(Int32 connectTimeOutSeconds) in D:\a\1Remote\1Remote\Ui\Service\DataSource\Model\DataSourceBase.Source.cs:line 186
   at _1RM.Service.DataSource.DataSourceService.InitLocalDataSource(SqliteSource sqliteConfig) in D:\a\1Remote\1Remote\Ui\Service\DataSource\DataSourceService.cs:line 83
   at _1RM.AppInitHelper.InitOnConfigure() in D:\a\1Remote\1Remote\Ui\AppInit.cs:line 275
   at _1RM.Bootstrapper.Configure() in D:\a\1Remote\1Remote\Ui\Bootstrapper.cs:line 89
   at Stylet.BootstrapperBase.Start(String[] args)
   at Stylet.BootstrapperBase.<Setup>b__9_0(Object o, StartupEventArgs e)
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at _1RM.App.OnStartup(StartupEventArgs e) in D:\a\1Remote\1Remote\Ui\App.xaml.cs:line 58
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
[T:001][21:50:36.511]	`Fatal`		[Bootstrapper.cs(OnUnhandledException:139)]	
> System.ArgumentNullException: Value cannot be null. (Parameter 'path1')
   at System.IO.Path.Combine(String path1, String path2)
   at System.Data.SQLite.SQLiteConnection..ctor(String connectionString, Boolean parseViaFramework)
   at System.Data.SQLite.SQLiteConnection..ctor(String connectionString)
   at _1RM.Service.DataSource.DAO.Dapper.DapperDatabase.OpenConnection(String actionInfo) in D:\a\1Remote\1Remote\Ui\Service\DataSource\DAO\Dapper\DapperDataBase.cs:line 85
   at _1RM.Service.DataSource.DAO.Dapper.DapperDatabase.OpenNewConnection(String newConnectionString) in D:\a\1Remote\1Remote\Ui\Service\DataSource\DAO\Dapper\DapperDataBase.cs:line 55
   at _1RM.Service.DataSource.Model.DataSourceBase.Database_OpenConnection(Int32 connectTimeOutSeconds) in D:\a\1Remote\1Remote\Ui\Service\DataSource\Model\DataSourceBase.Source.cs:line 166
   at _1RM.Service.DataSource.Model.DataSourceBase.Database_SelfCheck(Int32 connectTimeOutSeconds) in D:\a\1Remote\1Remote\Ui\Service\DataSource\Model\DataSourceBase.Source.cs:line 186
   at _1RM.Service.DataSource.DataSourceService.InitLocalDataSource(SqliteSource sqliteConfig) in D:\a\1Remote\1Remote\Ui\Service\DataSource\DataSourceService.cs:line 83
   at _1RM.AppInitHelper.InitOnConfigure() in D:\a\1Remote\1Remote\Ui\AppInit.cs:line 275
   at _1RM.Bootstrapper.Configure() in D:\a\1Remote\1Remote\Ui\Bootstrapper.cs:line 89
   at Stylet.BootstrapperBase.Start(String[] args)
   at Stylet.BootstrapperBase.<Setup>b__9_0(Object o, StartupEventArgs e)
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at _1RM.App.OnStartup(StartupEventArgs e) in D:\a\1Remote\1Remote\Ui\App.xaml.cs:line 58
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
> StackTrace:    at System.IO.Path.Combine(String path1, String path2)
   at System.Data.SQLite.SQLiteConnection..ctor(String connectionString, Boolean parseViaFramework)
   at System.Data.SQLite.SQLiteConnection..ctor(String connectionString)
   at _1RM.Service.DataSource.DAO.Dapper.DapperDatabase.OpenConnection(String actionInfo) in D:\a\1Remote\1Remote\Ui\Service\DataSource\DAO\Dapper\DapperDataBase.cs:line 85
   at _1RM.Service.DataSource.DAO.Dapper.DapperDatabase.OpenNewConnection(String newConnectionString) in D:\a\1Remote\1Remote\Ui\Service\DataSource\DAO\Dapper\DapperDataBase.cs:line 55
   at _1RM.Service.DataSource.Model.DataSourceBase.Database_OpenConnection(Int32 connectTimeOutSeconds) in D:\a\1Remote\1Remote\Ui\Service\DataSource\Model\DataSourceBase.Source.cs:line 166
   at _1RM.Service.DataSource.Model.DataSourceBase.Database_SelfCheck(Int32 connectTimeOutSeconds) in D:\a\1Remote\1Remote\Ui\Service\DataSource\Model\DataSourceBase.Source.cs:line 186
   at _1RM.Service.DataSource.DataSourceService.InitLocalDataSource(SqliteSource sqliteConfig) in D:\a\1Remote\1Remote\Ui\Service\DataSource\DataSourceService.cs:line 83
   at _1RM.AppInitHelper.InitOnConfigure() in D:\a\1Remote\1Remote\Ui\AppInit.cs:line 275
   at _1RM.Bootstrapper.Configure() in D:\a\1Remote\1Remote\Ui\Bootstrapper.cs:line 89
   at Stylet.BootstrapperBase.Start(String[] args)
   at Stylet.BootstrapperBase.<Setup>b__9_0(Object o, StartupEventArgs e)
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at _1RM.App.OnStartup(StartupEventArgs e) in D:\a\1Remote\1Remote\Ui\App.xaml.cs:line 58
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
[T:001][21:53:51.497]	`Fatal`		[Bootstrapper.cs(OnUnhandledException:139)]	
> System.ArgumentNullException: Value cannot be null. (Parameter 'path1')
   at System.IO.Path.Combine(String path1, String path2)
   at System.Data.SQLite.SQLiteConnection..ctor(String connectionString, Boolean parseViaFramework)
   at System.Data.SQLite.SQLiteConnection..ctor(String connectionString)
   at _1RM.Service.DataSource.DAO.Dapper.DapperDatabase.OpenConnection(String actionInfo) in D:\a\1Remote\1Remote\Ui\Service\DataSource\DAO\Dapper\DapperDataBase.cs:line 85
   at _1RM.Service.DataSource.DAO.Dapper.DapperDatabase.OpenNewConnection(String newConnectionString) in D:\a\1Remote\1Remote\Ui\Service\DataSource\DAO\Dapper\DapperDataBase.cs:line 55
   at _1RM.Service.DataSource.Model.DataSourceBase.Database_OpenConnection(Int32 connectTimeOutSeconds) in D:\a\1Remote\1Remote\Ui\Service\DataSource\Model\DataSourceBase.Source.cs:line 166
   at _1RM.Service.DataSource.Model.DataSourceBase.Database_SelfCheck(Int32 connectTimeOutSeconds) in D:\a\1Remote\1Remote\Ui\Service\DataSource\Model\DataSourceBase.Source.cs:line 186
   at _1RM.Service.DataSource.DataSourceService.InitLocalDataSource(SqliteSource sqliteConfig) in D:\a\1Remote\1Remote\Ui\Service\DataSource\DataSourceService.cs:line 83
   at _1RM.AppInitHelper.InitOnConfigure() in D:\a\1Remote\1Remote\Ui\AppInit.cs:line 275
   at _1RM.Bootstrapper.Configure() in D:\a\1Remote\1Remote\Ui\Bootstrapper.cs:line 89
   at Stylet.BootstrapperBase.Start(String[] args)
   at Stylet.BootstrapperBase.<Setup>b__9_0(Object o, StartupEventArgs e)
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at _1RM.App.OnStartup(StartupEventArgs e) in D:\a\1Remote\1Remote\Ui\App.xaml.cs:line 58
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
> StackTrace:    at System.IO.Path.Combine(String path1, String path2)
   at System.Data.SQLite.SQLiteConnection..ctor(String connectionString, Boolean parseViaFramework)
   at System.Data.SQLite.SQLiteConnection..ctor(String connectionString)
   at _1RM.Service.DataSource.DAO.Dapper.DapperDatabase.OpenConnection(String actionInfo) in D:\a\1Remote\1Remote\Ui\Service\DataSource\DAO\Dapper\DapperDataBase.cs:line 85
   at _1RM.Service.DataSource.DAO.Dapper.DapperDatabase.OpenNewConnection(String newConnectionString) in D:\a\1Remote\1Remote\Ui\Service\DataSource\DAO\Dapper\DapperDataBase.cs:line 55
   at _1RM.Service.DataSource.Model.DataSourceBase.Database_OpenConnection(Int32 connectTimeOutSeconds) in D:\a\1Remote\1Remote\Ui\Service\DataSource\Model\DataSourceBase.Source.cs:line 166
   at _1RM.Service.DataSource.Model.DataSourceBase.Database_SelfCheck(Int32 connectTimeOutSeconds) in D:\a\1Remote\1Remote\Ui\Service\DataSource\Model\DataSourceBase.Source.cs:line 186
   at _1RM.Service.DataSource.DataSourceService.InitLocalDataSource(SqliteSource sqliteConfig) in D:\a\1Remote\1Remote\Ui\Service\DataSource\DataSourceService.cs:line 83
   at _1RM.AppInitHelper.InitOnConfigure() in D:\a\1Remote\1Remote\Ui\AppInit.cs:line 275
   at _1RM.Bootstrapper.Configure() in D:\a\1Remote\1Remote\Ui\Bootstrapper.cs:line 89
   at Stylet.BootstrapperBase.Start(String[] args)
   at Stylet.BootstrapperBase.<Setup>b__9_0(Object o, StartupEventArgs e)
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at _1RM.App.OnStartup(StartupEventArgs e) in D:\a\1Remote\1Remote\Ui\App.xaml.cs:line 58
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

```

</details>

**Comment by VShawn** [comment]
ehh, could you please show me what is '...'?

**Comment by aleck31** [comment]
> > Go to '...'
> > Click on '....'
> > Scroll down to '....'
> 
> Uhh, could you please show me what is `...`?

These come from issues template, please expand the [Details].
According to my test on two different clients, the last version that can run on windows11 is the nightly-20230623-d398e9.

**Comment by majkinetor** [comment]
Try latest nightly please.

https://github.com/1Remote/1Remote/releases/download/Nightly/1Remote-1.0.0.0-beta.05-net6-x64-nightly-20230703-fd92d0.zip

**Comment by aleck31** [comment]
> Try latest nightly please.
> 
> https://github.com/1Remote/1Remote/releases/download/Nightly/1Remote-1.0.0.0-beta.05-net6-x64-nightly-20230703-fd92d0.zip

I mean, it doesn't work since nightly-20230623-d398e9.

these later versions, listed below, do not work:
nightly-20230624-bc8488
nightly-20230701-e6659e
nightly-20230702-6b3237
nightly-20230703-fd92d0

**Comment by VShawn** [comment]
ahh sorry I did not see your Stack Trace...

---

About this error, you can see:

https://github.com/1Remote/1Remote/issues/439#issuecomment-1617055165

and

https://github.com/1Remote/1Remote/issues/439#issuecomment-1617458384

Could you double check the `1Remote-1.0.0.0-beta.05-net6-x64-nightly-20230703-fd92d0.zip`? it works on both our win11 win10 test env.

**Comment by aleck31** [comment]
> 
After I replace both 1Remote.exe and SQLite.Interop.dll files with new version(nightly-20230703-fd92d0), it works fine now.  Well done ~
