### ISSUE TITLE
Catastrophic failure when running RDP connection

### ISSUE THREAD

**Issue by majkinetor** [1Remote/1Remote#451]
[T:001][09:01:03.939]	`Warning`		[ServerSelectionsViewModel.cs(<set_Filter>b__0:71)]	CalcVisibleByFilter

[T:001][09:01:04.251]	`Warning`		[ServerSelectionsViewModel.cs(<set_Filter>b__0:71)]	CalcVisibleByFilter

[T:001][09:01:04.671]	`Warning`		[ServerSelectionsViewModel.cs(<set_Filter>b__0:71)]	CalcVisibleByFilter

[T:001][15:07:48.705]	`Error`		[AxMsRdpClient09Host.xaml.cs(<SetRdpResolution>b__0:823)]	
> System.Runtime.InteropServices.COMException (0x8000FFFF): Catastrophic failure (0x8000FFFF (E_UNEXPECTED))
   at MSTSCLib.IMsRdpClient9.UpdateSessionDisplaySettings(UInt32 ulDesktopWidth, UInt32 ulDesktopHeight, UInt32 ulPhysicalWidth, UInt32 ulPhysicalHeight, UInt32 ulOrientation, UInt32 ulDesktopScaleFactor, UInt32 ulDeviceScaleFactor)
   at AxMSTSCLib.AxMsRdpClient9NotSafeForScripting.UpdateSessionDisplaySettings(UInt32 ulDesktopWidth, UInt32 ulDesktopHeight, UInt32 ulPhysicalWidth, UInt32 ulPhysicalHeight, UInt32 ulOrientation, UInt32 ulDesktopScaleFactor, UInt32 ulDeviceScaleFactor)
   at _1RM.View.Host.ProtocolHosts.AxMsRdpClient09Host.<>c__DisplayClass51_0.<SetRdpResolution>b__0() in D:\a\1Remote\1Remote\Ui\View\Host\ProtocolHosts\AxMsRdpClient09Host.xaml.cs:line 823

> StackTrace:    at MSTSCLib.IMsRdpClient9.UpdateSessionDisplaySettings(UInt32 ulDesktopWidth, UInt32 ulDesktopHeight, UInt32 ulPhysicalWidth, UInt32 ulPhysicalHeight, UInt32 ulOrientation, UInt32 ulDesktopScaleFactor, UInt32 ulDeviceScaleFactor)
   at AxMSTSCLib.AxMsRdpClient9NotSafeForScripting.UpdateSessionDisplaySettings(UInt32 ulDesktopWidth, UInt32 ulDesktopHeight, UInt32 ulPhysicalWidth, UInt32 ulPhysicalHeight, UInt32 ulOrientation, UInt32 ulDesktopScaleFactor, UInt32 ulDeviceScaleFactor)
   at _1RM.View.Host.ProtocolHosts.AxMsRdpClient09Host.<>c__DisplayClass51_0.<SetRdpResolution>b__0() in D:\a\1Remote\1Remote\Ui\View\Host\ProtocolHosts\AxMsRdpClient09Host.xaml.cs:line 823

**Comment by VShawn** [comment]
App crashed?

I do place a `try...catch` there.

https://github.com/1Remote/1Remote/blob/bceb2928f1fac9afdef16f1ad9c9c7d78c379202/Ui/View/Host/ProtocolHosts/AxMsRdpClient09Host.xaml.cs#L812-L830

If this code is called before RDP desktop is displayed, the error will occur. Unfortunately, Microsoft does not provide an interface to detect if the RDP desktop login has displayed. I know there is an "OnLoginComplete" callback, but it has been tested and found that it does not trigger after the RDP desktop is displayed.

**Comment by majkinetor** [comment]
Yes it crashed.

As far as I can say, there i logon screen active remotelly when it crashed, and after I restarted the connection, it displayed the desktop immediatelly.
