### ISSUE TITLE
Crash when running under Windows Server 2008 R2

### ISSUE THREAD

**Issue by shamork** [1Remote/1Remote#461]
Crash when running under Windows Server 2008 R2

**To Reproduce**
just run the PRemoteM.exe

**Expected behavior**
works

**Screenshots**
(None)

**Desktop (please complete the following information):**
 - OS: [e.g. Win10 Pro 2004]
 - PRemoteM Version [e.g. 0.7.2.8]

**Additional context**

## Environment

|     Component   |                       Version                      |
|:------------------|:--------------------------------------|
|PRemoteM | `0.7.2.8`(EXE Release)|
|.NET Framework | ``    |
|CLR            | `6.0.11`       |
|OS             | `Windows Server 2008 R2 Enterprise 64-bits 6.1.7601.0 ()`                  |

## InnerException Info

The type initializer for 'Microsoft.AppCenter.Utils.WindowsHelper' threw an exception.

## InnerException Stack Trace

```
   at Microsoft.AppCenter.Utils.WindowsHelper.add_OnMinimized(WinEventDelegate value)
   at Microsoft.AppCenter.Utils.ApplicationLifecycleHelperDesktop..cctor()
```

## Error Info

The type initializer for 'Microsoft.AppCenter.Utils.ApplicationLifecycleHelperDesktop' threw an exception.

## Stack Trace

```
   at Microsoft.AppCenter.Utils.ApplicationLifecycleHelperDesktop..ctor()
   at Microsoft.AppCenter.ApplicationLifecycleHelper.get_Instance()
   at Microsoft.AppCenter.AppCenter..ctor()
   at Microsoft.AppCenter.AppCenter.get_Instance()
   at Microsoft.AppCenter.AppCenter.PlatformStart(String appSecret, Type[] services)
   at Microsoft.AppCenter.AppCenter.Start(String appSecret, Type[] services)
   at PRM.Utils.MsAppCenterHelper.Init(String secret) in D:\a\1Remote\1Remote\Ui\Utils\MsAppCenterHelper.cs:line 39
   at Ui.App.OnStartup(StartupEventArgs e) in D:\a\1Remote\1Remote\Ui\App.xaml.cs:line 19
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

## Recent Log 

```
[T:001][13:15:15.764]	`Fatal`		[Bootstrapper.cs(OnUnhandledException:164)]	
> System.TypeInitializationException: The type initializer for 'Microsoft.AppCenter.Utils.ApplicationLifecycleHelperDesktop' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'Microsoft.AppCenter.Utils.WindowsHelper' threw an exception.
 ---> System.EntryPointNotFoundException: Unable to find an entry point named 'GetCurrentPackageFullName' in DLL 'kernel32.dll'.
   at Microsoft.AppCenter.Utils.WindowsHelper.GetCurrentPackageFullName(Int32& packageFullNameLength, StringBuilder packageFullName)
   at Microsoft.AppCenter.Utils.WindowsHelper._IsRunningAsUwp()
   at Microsoft.AppCenter.Utils.WindowsHelper..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.AppCenter.Utils.WindowsHelper.add_OnMinimized(WinEventDelegate value)
   at Microsoft.AppCenter.Utils.ApplicationLifecycleHelperDesktop..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.AppCenter.Utils.ApplicationLifecycleHelperDesktop..ctor()
   at Microsoft.AppCenter.ApplicationLifecycleHelper.get_Instance()
   at Microsoft.AppCenter.AppCenter..ctor()
   at Microsoft.AppCenter.AppCenter.get_Instance()
   at Microsoft.AppCenter.AppCenter.PlatformStart(String appSecret, Type[] services)
   at Microsoft.AppCenter.AppCenter.Start(String appSecret, Type[] services)
   at PRM.Utils.MsAppCenterHelper.Init(String secret) in D:\a\1Remote\1Remote\Ui\Utils\MsAppCenterHelper.cs:line 39
   at Ui.App.OnStartup(StartupEventArgs e) in D:\a\1Remote\1Remote\Ui\App.xaml.cs:line 19
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
> StackTrace:    at Microsoft.AppCenter.Utils.ApplicationLifecycleHelperDesktop..ctor()
   at Microsoft.AppCenter.ApplicationLifecycleHelper.get_Instance()
   at Microsoft.AppCenter.AppCenter..ctor()
   at Microsoft.AppCenter.AppCenter.get_Instance()
   at Microsoft.AppCenter.AppCenter.PlatformStart(String appSecret, Type[] services)
   at Microsoft.AppCenter.AppCenter.Start(String appSecret, Type[] services)
   at PRM.Utils.MsAppCenterHelper.Init(String secret) in D:\a\1Remote\1Remote\Ui\Utils\MsAppCenterHelper.cs:line 39
   at Ui.App.OnStartup(StartupEventArgs e) in D:\a\1Remote\1Remote\Ui\App.xaml.cs:line 19
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
> InnerException: The type initializer for 'Microsoft.AppCenter.Utils.WindowsHelper' threw an exception.
> Inner StackTrace:    at Microsoft.AppCenter.Utils.WindowsHelper.add_OnMinimized(WinEventDelegate value)
   at Microsoft.AppCenter.Utils.ApplicationLifecycleHelperDesktop..cctor()

```

</details>

**Comment by VShawn** [comment]
the package Microsoft.AppCenter do not support OS < Win10, that's why it crash.

I'm working on the package now, and it is currently unclear whether it can be fixed or not.

**Comment by VShawn** [comment]
@shamork Hey could you help test the latest net48 version on win2008? I can't test it because I dont have a win2008.

you can get net48 artifact here:

https://github.com/1Remote/1Remote/actions/runs/5689079638

**Comment by VShawn** [comment]
I think we are not able to make a exe can runing on both win7 win2008 win10 win11. Since our requirement is Win10 and above, I will not spend any more time on this ticket.
