### ISSUE TITLE
第一次打开报错

### ISSUE THREAD

**Issue by upcliujie** [1Remote/1Remote#506]
第一次打开报错：
<details>

## Environment

|     Component   |                       Version                      |
|:------------------|:--------------------------------------|
|PRemoteM | `0.7.2.8`(EXE Release)|
|.NET Framework | ``    |
|CLR            | `6.0.16`       |
|OS             | `Windows 10 Pro 64-bits 10.0.22621.0 (2009)`                  |

## Error Info

Access to the path 'C:\Program Files\PRemoteM\Protocols' is denied.

## Stack Trace

```
   at System.IO.FileSystem.CreateDirectory(String fullPath, Byte[] securityDescriptor)
   at System.IO.DirectoryInfo.Create()
   at PRM.AppInit.CreateDirIfNotExist(String path, Boolean isFile) in D:\a\1Remote\1Remote\Ui\AppInit.cs:line 58
   at PRM.AppInit.InitOnStart() in D:\a\1Remote\1Remote\Ui\AppInit.cs:line 225
   at PRM.Bootstrapper.OnStart() in D:\a\1Remote\1Remote\Ui\Bootstrapper.cs:line 77
   at Stylet.BootstrapperBase.Start(String[] args)
   at Stylet.BootstrapperBase.<Setup>b__9_0(Object o, StartupEventArgs e)
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at Ui.App.OnStartup(StartupEventArgs e) in D:\a\1Remote\1Remote\Ui\App.xaml.cs:line 22
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

## Recent Log 

```

```

</details>

**Comment by VShawn** [comment]
错误信息已经写明了，没权限写入文件到 'C:\Program Files\PRemoteM\Protocols'
