### ISSUE TITLE
外网vnc内网mac机器卡住不动,其他vnc同环境没问题

### ISSUE THREAD

**Issue by noidnoid** [1Remote/1Remote#521]
log文件
[T:056][17:34:06.396]	`Warning`		[SessionControlService.cs(<CloseProtocolHostAsync>b__0:698)]	CloseEmptyWindows: 1 Empty Host closed

[T:056][17:34:09.413]	`Error`		[SessionControlService.cs(CloseMarkedProtocolHost:828)]	
> System.InvalidOperationException: 调用线程无法访问此对象，因为另一个线程拥有该对象。
   at System.Windows.Threading.Dispatcher.VerifyAccess()
   at System.Windows.DependencyObject.SetValue(DependencyProperty dp, Object value)
   at PRM.View.Host.ProtocolHosts.VncHost.OnConnectionLost(Object sender, EventArgs e) in D:\a\1Remote\1Remote\Ui\View\Host\ProtocolHosts\VncHost.xaml.cs:line 158
   at VncSharpCore.RemoteDesktop.OnConnectionLost() in D:\a\1Remote\1Remote\VncSharpCore\VncSharpCore\RemoteDesktop.cs:line 742
   at VncSharpCore.RemoteDesktop.Disconnect() in D:\a\1Remote\1Remote\VncSharpCore\VncSharpCore\RemoteDesktop.cs:line 593
   at PRM.View.Host.ProtocolHosts.VncHost.Close() in D:\a\1Remote\1Remote\Ui\View\Host\ProtocolHosts\VncHost.xaml.cs:line 124
   at PRM.Service.SessionControlService.CloseMarkedProtocolHost() in D:\a\1Remote\1Remote\Ui\Service\SessionControlService.cs:line 828

> StackTrace:    at System.Windows.Threading.Dispatcher.VerifyAccess()
   at System.Windows.DependencyObject.SetValue(DependencyProperty dp, Object value)
   at PRM.View.Host.ProtocolHosts.VncHost.OnConnectionLost(Object sender, EventArgs e) in D:\a\1Remote\1Remote\Ui\View\Host\ProtocolHosts\VncHost.xaml.cs:line 158
   at VncSharpCore.RemoteDesktop.OnConnectionLost() in D:\a\1Remote\1Remote\VncSharpCore\VncSharpCore\RemoteDesktop.cs:line 742
   at VncSharpCore.RemoteDesktop.Disconnect() in D:\a\1Remote\1Remote\VncSharpCore\VncSharpCore\RemoteDesktop.cs:line 593
   at PRM.View.Host.ProtocolHosts.VncHost.Close() in D:\a\1Remote\1Remote\Ui\View\Host\ProtocolHosts\VncHost.xaml.cs:line 124
   at PRM.Service.SessionControlService.CloseMarkedProtocolHost() in D:\a\1Remote\1Remote\Ui\Service\SessionControlService.cs:line 828

**Comment by VShawn** [comment]
看日志信息应该是发生了bug。能顺带告知一下版本么？

**Comment by noidnoid** [comment]
0.7.2.8

**Comment by VShawn** [comment]
貌似需要修改 VncSharp 项目，但这个项目从2019年起就已经没人维护了，所以还是不改了。

后续会考虑过集成 TightVNC 替换掉现在的 VncSharp.

作为临时解决方案，建议你把 VNC 的runner 配置为 TightVNC

![image](https://github.com/1Remote/1Remote/assets/10143738/f188a92a-83de-45be-9e59-7a97ff2e219e)
