### ISSUE TITLE
Ioc can not get an item.

### ISSUE THREAD

**Issue by mrcssilvasouza** [1Remote/1Remote#590]
<details>

## Environment

|     Component   |                       Version                      |
|:------------------|:--------------------------------------|
|1Remote | `0.4.0-alpha.01`(EXE Release)|
|.NET Framework | ``    |
|CLR            | `6.0.25`       |
|OS             | `Windows 10 Pro 64-bits 10.0.22000.0 (2009)`                  |

## Error Info

Ioc can not get an item.

## Stack Trace

```
   at _1RM.IoC.Get[T](String key) in D:\a\1Remote\1Remote\Ui\Ioc.cs:line 27
   at _1RM.Utils.MessageBoxHelper.ErrorAlert(String content, String title, Boolean useNativeBox, IViewAware ownerViewModel) in D:\a\1Remote\1Remote\Ui\Utils\MessageBoxHelper.cs:line 122
   at _1RM.AppInit.WritePermissionCheck(String path, Boolean isFile) in D:\a\1Remote\1Remote\Ui\AppInit.cs:line 31
   at _1RM.AppInit.InitOnStart() in D:\a\1Remote\1Remote\Ui\AppInit.cs:line 198
   at _1RM.Bootstrapper.OnStart() in D:\a\1Remote\1Remote\Ui\Bootstrapper.cs:line 73
   at Stylet.BootstrapperBase.Start(String[] args)
   at Stylet.BootstrapperBase.<Setup>b__9_0(Object o, StartupEventArgs e)
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at _1RM.App.OnStartup(StartupEventArgs e) in D:\a\1Remote\1Remote\Ui\App.xaml.cs:line 18
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by VShawn** [comment]
oh please upgrade to 1.0.0 beta version, `0.4.0-alpha.01` is tooo old
