### ISSUE TITLE
unexpected error occured when start the application from win7

### ISSUE THREAD

**Issue by ptcgh** [1Remote/1Remote#635]
**Describe the bug**

**To Reproduce**
1. start the program 

**Expected behavior**
<details>

## Environment

|     Component   |                       Version                      |
|:------------------|:--------------------------------------|
|PRemoteM | `0.7.2.8`(EXE Release)|
|.NET Framework | ``    |
|CLR            | `6.0.28`       |
|OS             | `Windows 7 Home Premium 64-bits 6.1.7601.0 ()`                  |

## InnerException Info

The type initializer for 'Microsoft.AppCenter.Utils.WindowsHelper' threw an exception.

## InnerException Stack Trace

```
   at Microsoft.AppCenter.Utils.WindowsHelper.add_OnMinimized(WinEventDelegate value)
   at Microsoft.AppCenter.Utils.ApplicationLifecycleHelperDesktop..cctor()
```

## Error Info

The type initializer for 'Microsoft.AppCenter.Utils.ApplicationLifecycleHelperDesktop' threw an exception.

## Stack Trace

```
   at Microsoft.AppCenter.Utils.ApplicationLifecycleHelperDesktop..ctor()
   at Microsoft.AppCenter.ApplicationLifecycleHelper.get_Instance()
   at Microsoft.AppCenter.AppCenter..ctor()
   at Microsoft.AppCenter.AppCenter.get_Instance()
   at Microsoft.AppCenter.AppCenter.PlatformStart(String appSecret, Type[] services)
   at Microsoft.AppCenter.AppCenter.Start(String appSecret, Type[] services)
   at PRM.Utils.MsAppCenterHelper.Init(String secret) in D:\a\1Remote\1Remote\Ui\Utils\MsAppCenterHelper.cs:line 39
   at Ui.App.OnStartup(StartupEventArgs e) in D:\a\1Remote\1Remote\Ui\App.xaml.cs:line 19
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

## Recent Log 

```
[T:001][08:27:52.911]	`Fatal`		[Bootstrapper.cs(OnUnhandledException:164)]	
> System.TypeInitializationException: The type initializer for 'Microsoft.AppCenter.Utils.ApplicationLifecycleHelperDesktop' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'Microsoft.AppCenter.Utils.WindowsHelper' threw an exception.
 ---> System.EntryPointNotFoundException: Unable to find an entry point named 'GetCurrentPackageFullName' in DLL 'kernel32.dll'.
   at Microsoft.AppCenter.Utils.WindowsHelper.GetCurrentPackageFullName(Int32& packageFullNameLength, StringBuilder packageFullName)
   at Microsoft.AppCenter.Utils.WindowsHelper._IsRunningAsUwp()
   at Microsoft.AppCenter.Utils.WindowsHelper..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.AppCenter.Utils.WindowsHelper.add_OnMinimized(WinEventDelegate value)
   at Microsoft.AppCenter.Utils.ApplicationLifecycleHelperDesktop..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.AppCenter.Utils.ApplicationLifecycleHelperDesktop..ctor()
   at Microsoft.AppCenter.ApplicationLifecycleHelper.get_Instance()
   at Microsoft.AppCenter.AppCenter..ctor()
   at Microsoft.AppCenter.AppCenter.get_Instance()
   at Microsoft.AppCenter.AppCenter.PlatformStart(String appSecret, Type[] services)
   at Microsoft.AppCenter.AppCenter.Start(String appSecret, Type[] services)
   at PRM.Utils.MsAppCenterHelper.Init(String secret) in D:\a\1Remote\1Remote\Ui\Utils\MsAppCenterHelper.cs:line 39
   at Ui.App.OnStartup(StartupEventArgs e) in D:\a\1Remote\1Remote\Ui\App.xaml.cs:line 19
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
> StackTrace:    at Microsoft.AppCenter.Utils.ApplicationLifecycleHelperDesktop..ctor()
   at Microsoft.AppCenter.ApplicationLifecycleHelper.get_Instance()
   at Microsoft.AppCenter.AppCenter..ctor()
   at Microsoft.AppCenter.AppCenter.get_Instance()
   at Microsoft.AppCenter.AppCenter.PlatformStart(String appSecret, Type[] services)
   at Microsoft.AppCenter.AppCenter.Start(String appSecret, Type[] services)
   at PRM.Utils.MsAppCenterHelper.Init(String secret) in D:\a\1Remote\1Remote\Ui\Utils\MsAppCenterHelper.cs:line 39
   at Ui.App.OnStartup(StartupEventArgs e) in D:\a\1Remote\1Remote\Ui\App.xaml.cs:line 19
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
> InnerException: The type initializer for 'Microsoft.AppCenter.Utils.WindowsHelper' threw an exception.
> Inner StackTrace:    at Microsoft.AppCenter.Utils.WindowsHelper.add_OnMinimized(WinEventDelegate value)
   at Microsoft.AppCenter.Utils.ApplicationLifecycleHelperDesktop..cctor()
[T:001][08:28:47.100]	`Fatal`		[Bootstrapper.cs(OnUnhandledException:164)]	
> System.TypeInitializationException: The type initializer for 'Microsoft.AppCenter.Utils.ApplicationLifecycleHelperDesktop' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'Microsoft.AppCenter.Utils.WindowsHelper' threw an exception.
 ---> System.EntryPointNotFoundException: Unable to find an entry point named 'GetCurrentPackageFullName' in DLL 'kernel32.dll'.
   at Microsoft.AppCenter.Utils.WindowsHelper.GetCurrentPackageFullName(Int32& packageFullNameLength, StringBuilder packageFullName)
   at Microsoft.AppCenter.Utils.WindowsHelper._IsRunningAsUwp()
   at Microsoft.AppCenter.Utils.WindowsHelper..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.AppCenter.Utils.WindowsHelper.add_OnMinimized(WinEventDelegate value)
   at Microsoft.AppCenter.Utils.ApplicationLifecycleHelperDesktop..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.AppCenter.Utils.ApplicationLifecycleHelperDesktop..ctor()
   at Microsoft.AppCenter.ApplicationLifecycleHelper.get_Instance()
   at Microsoft.AppCenter.AppCenter..ctor()
   at Microsoft.AppCenter.AppCenter.get_Instance()
   at Microsoft.AppCenter.AppCenter.PlatformStart(String appSecret, Type[] services)
   at Microsoft.AppCenter.AppCenter.Start(String appSecret, Type[] services)
   at PRM.Utils.MsAppCenterHelper.Init(String secret) in D:\a\1Remote\1Remote\Ui\Utils\MsAppCenterHelper.cs:line 39
   at Ui.App.OnStartup(StartupEventArgs e) in D:\a\1Remote\1Remote\Ui\App.xaml.cs:line 19
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
> StackTrace:    at Microsoft.AppCenter.Utils.ApplicationLifecycleHelperDesktop..ctor()
   at Microsoft.AppCenter.ApplicationLifecycleHelper.get_Instance()
   at Microsoft.AppCenter.AppCenter..ctor()
   at Microsoft.AppCenter.AppCenter.get_Instance()
   at Microsoft.AppCenter.AppCenter.PlatformStart(String appSecret, Type[] services)
   at Microsoft.AppCenter.AppCenter.Start(String appSecret, Type[] services)
   at PRM.Utils.MsAppCenterHelper.Init(String secret) in D:\a\1Remote\1Remote\Ui\Utils\MsAppCenterHelper.cs:line 39
   at Ui.App.OnStartup(StartupEventArgs e) in D:\a\1Remote\1Remote\Ui\App.xaml.cs:line 19
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
> InnerException: The type initializer for 'Microsoft.AppCenter.Utils.WindowsHelper' threw an exception.
> Inner StackTrace:    at Microsoft.AppCenter.Utils.WindowsHelper.add_OnMinimized(WinEventDelegate value)
   at Microsoft.AppCenter.Utils.ApplicationLifecycleHelperDesktop..cctor()

```

</details>

**Screenshots**

**Desktop (please complete the following information):**
 - OS:Windows 7 Home Premium 64-bits 6.1.7601.0 ()
 - PRemoteM Version 0.7.2.8

**Additional context**

**Comment by VShawn** [comment]
sorry, win7 is not supported now.
